message( STATUS "ScaLAPACK_VENDOR              = ${ScaLAPACK_VENDOR}"              )
message( STATUS "ScaLAPACK_LIBRARIES           = ${ScaLAPACK_LIBRARIES}"           )
message( STATUS "ScaLAPACK_COMPILE_DEFINITIONS = ${ScaLAPACK_COMPILE_DEFINITIONS}" )
message( STATUS "ScaLAPACK_COMPILE_OPTIONS     = ${ScaLAPACK_COMPILE_OPTIONS}"     )
foreach (lang C CXX Fortran)
    if (DEFINED ScaLAPACK_${lang}_COMPILE_OPTIONS)
        message( STATUS "ScaLAPACK_${lang}_COMPILE_OPTIONS     = ${ScaLAPACK_${lang}_COMPILE_OPTIONS}"     )
    endif()
endforeach()
message( STATUS "ScaLAPACK_FORTRAN_LOWER       = ${ScaLAPACK_FORTRAN_LOWER}"       )
message( STATUS "ScaLAPACK_FORTRAN_UNDERSCORE  = ${ScaLAPACK_FORTRAN_UNDERSCORE}"  )
message( STATUS "ScaLAPACK_IS_LP64             = ${ScaLAPACK_IS_LP64}"             )
