message( STATUS "BLAS_VENDOR              = ${BLAS_VENDOR}"              )
message( STATUS "BLAS_LIBRARIES           = ${BLAS_LIBRARIES}"           )
message( STATUS "BLAS_COMPILE_DEFINITIONS = ${BLAS_COMPILE_DEFINITIONS}" )
message( STATUS "BLAS_COMPILE_OPTIONS     = ${BLAS_COMPILE_OPTIONS}"     )
foreach (lang C CXX Fortran)
    if (DEFINED BLAS_${lang}_COMPILE_OPTIONS)
        message( STATUS "BLAS_${lang}_COMPILE_OPTIONS     = ${BLAS_${lang}_COMPILE_OPTIONS}"     )
    endif()
endforeach()
message( STATUS "BLAS_Fortran_LOWER       = ${BLAS_Fortran_LOWER}"       )
message( STATUS "BLAS_Fortran_UNDERSCORE  = ${BLAS_Fortran_UNDERSCORE}"  )
message( STATUS "BLAS_IS_LP64             = ${BLAS_IS_LP64}"             )
